# Generated by Django 5.0.2 on 2024-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('avatar', models.ImageField(upload_to='media/')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
