# Generated by Django 5.0.2 on 2024-02-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
            preserve_default=False,
        ),
    ]
