# Generated by Django 5.0.2 on 2024-02-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_category_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
            preserve_default=False,
        ),
    ]
