# Generated by Django 5.0.2 on 2024-02-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_category_user_role_user_userprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
