# Generated by Django 5.0.2 on 2024-02-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_blogpost_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='blog_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='home.blogpost'),
            preserve_default=False,
        ),
    ]
