# Generated by Django 5.0.2 on 2024-02-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_category_userprofile_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='categories',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog_posts',
        ),
    ]
